Horeca.PresentationLayer.bak/Controllers/IdentificationController.cs
using Horeca.BusinessLayer.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Net.Http;
using System.Text;
using System.Threading.Tasks;

namespace Horeca.PresentationLayer.Controllers
{
	public class IdentificationController : Controller
	{
		private readonly HttpClient Client = new HttpClient();
		private const string BaseUrl = "https://localhost:5003/api/Identification";
		
		//private readonly string BaseUrl;
		//private readonly IConfiguration Configuration;

		//public IdentificationController(IConfiguration configuration)
		//{
		//	Configuration = configuration;
		//	BaseUrl = Configuration["IdentificationsAPI:Url"];
		//}
	
		// GET: IdentificationController
		public async Task<ActionResult> Index()
		{
			try
			{
				var httpResponse = await Client.GetAsync(BaseUrl);

				if (!httpResponse.IsSuccessStatusCode)
				{
					throw new Exception("Cannot retieve this Identificatons !");
				}

				var content = await httpResponse.Content.ReadAsStringAsync();

				var result = JsonConvert.DeserializeObject<IEnumerable<IdentificationModel>>(content);

				return View(result);
			}
			
			catch (Exception ex)
			{
				TempData["Message"] = ex;
				return RedirectToAction("Error","Shared");
			}
		}

		// GET: IdentificationController/Details/5
		public async Task<ActionResult> Details(int id)
		{
			var httpResponse = await Client.GetAsync($"{BaseUrl}/{id}");

			if (!httpResponse.IsSuccessStatusCode)
			{
				throw new Exception("Cannot retieve this Identification !");
			}

			var content = await httpResponse.Content.ReadAsStringAsync();

			var result = JsonConvert.DeserializeObject<IdentificationModel>(content);

			return View(result);
		}

		// GET: IdentificationController/Create
		[HttpGet]
		public ActionResult Create()
		{
			return View();
		}

		// POST: IdentificationController/Create
		[HttpPost]
		[ValidateAntiForgeryToken]
		public async Task<ActionResult> Create([Bind ("Type", "Name", "VatNumber", "EmailAddress", "Description")] IdentificationModel task)
		{
			try
			{ 
				var content = JsonConvert.SerializeObject(task);
				var httpResponse = await Client.PostAsync(BaseUrl, new StringContent(content, Encoding.Default, "application/json"));

				if (!httpResponse.IsSuccessStatusCode)
				{
					throw new Exception("Cannot create this Identification !");
				}

				TempData["Message"] = "This Identification is create successfully !";
				return RedirectToAction("Index");
			}

			catch (Exception ex)
			{
				TempData["Message"] = ex;
				return RedirectToAction("Error", "Shared");
			}
		}

		// GET: IdentificationController/Edit/5
		[HttpGet]
		public async Task<ActionResult> Edit(int id)
		{
			try
			{
				var httpResponse = await Client.GetAsync($"{BaseUrl}/{id}");


				if (!httpResponse.IsSuccessStatusCode)
				{
					throw new Exception("Cannot retrieve this Identification !");
				}

				var content = await httpResponse.Content.ReadAsStringAsync();

				var result = JsonConvert.DeserializeObject<IdentificationModel>(content);

				return View(result);
			}

			catch (Exception ex)
			{
				TempData["Message"] = ex;
				return RedirectToAction("Error", "Shared");
			}
		}

		// POST: IdentificationController/Edit/5
		[HttpPost]
		[ValidateAntiForgeryToken]
		public async Task<ActionResult> Edit([Bind("Id", "Type", "Name", "VatNumber", "EmailAddress", "Description")] IdentificationModel task)
		{
			try
			{
				var content = JsonConvert.SerializeObject(task);
				
				var httpResponse = await Client.PutAsync($"{BaseUrl}/{task.Id}", new StringContent(content, Encoding.Default, "application/json"));
				
				if (!httpResponse.IsSuccessStatusCode)
				{
					throw new Exception("Cannot Edit this Identification !");
				}

				TempData["Message"] = "This Identification was update successfully !";

				return RedirectToAction("Index");
			}

			catch (Exception ex)
			{
				TempData["Message"] = ex;
				return RedirectToAction("Error", "Shared");
			}
		}

		// GET: IdentificationController/Delete/5
		[HttpGet]
		public async Task<ActionResult> Delete(int id)
		{
			try
			{
				var httpResponse = await Client.GetAsync($"{BaseUrl}/{id}");

				if (!httpResponse.IsSuccessStatusCode)
				{
					throw new Exception("Cannot retieve this Identification");
				}

				var content = await httpResponse.Content.ReadAsStringAsync();

				var result = JsonConvert.DeserializeObject<IdentificationModel>(content);

				return View(result);
			}

			catch (Exception ex)
			{
				TempData["Message"] = ex;
				return RedirectToAction("Error", "Shared");
			}
		}

		// POST: IdentificationController/Delete/5
		[HttpPost]
		[ValidateAntiForgeryToken]
		public async Task<ActionResult> Delete([Bind("Id", "Type", "Name", "VatNumber", "EmailAddress", "Description")] IdentificationModel task)
		{
			try
			{
				var httpResponse = await Client.DeleteAsync($"{BaseUrl}/{task.Id}");

				if (!httpResponse.IsSuccessStatusCode)
				{
					throw new Exception("Cannot retieve tasks");
				}

				TempData["Message"] = "This Idendification was delete successfully !";

				return RedirectToAction("Index");
			}

			catch
			{
				return View();
			}
		}
	}
}

Horeca.PresentationLayer.bak/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Horeca.PresentationLayer</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <style>
        /* Set the size of the div element that contains the map */
        #map {
            height: 400px; /* The height is 400 pixels */
            width: 100%; /* The width is the width of the web page */
        }
    </style>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Horeca.PresentationLayer</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Identification" asp-action="Index">Identifications</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @if (!(TempData["Message"] is null))

            {

                <div class="alert alert-info">

                    @TempData["Message"];

                </div>

            }
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - Horeca.PresentationLayer - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>